services:
    MetaModels\CoreBundle\Contao\InsertTag\ReplaceTableName:
        public: false

    MetaModels\CoreBundle\Contao\InsertTag\ReplaceParam:
        public: false
        arguments:
            - '@metamodels.contao_input'
            - '@metamodels.contao_session'

    MetaModels\CoreBundle\Contao\InsertTag\ResolveLanguageTag:
        public: false
        arguments:
            - '@request_stack'
